defmodule OrcaHub.MCP.CodeExec.MetaTools do
  @moduledoc """
  The collapsed MCP tool surface presented to a code-exec session.

  When `code_exec` is enabled for a connection, `tools/list` returns exactly
  ONE tool:

    * `run_elixir` — evaluate model-authored Elixir that calls tools as named
      `Tools.*` functions and stitches results with stdlib

  Every first-party AND upstream tool — `send_message_to_session`,
  `get_session_tail`, `report_progress`, the feature-request tools,
  `start_session`/`search_sessions`/`schedule_heartbeat`, upstream tools like
  `github__get_issue`, all of it — is reachable ONLY as a `Tools.*` function
  called from inside `run_elixir`, discoverable there via `Tools.search/1`,
  `Tools.list/0`, and `Tools.schema/1`. `run_elixir`'s own description is the
  entire onboarding surface for this connection, so it documents discovery
  and advertises the handful of tools a session calls most often (see
  `run_elixir_description/0`).

  Two standalone tools this module used to expose no longer exist, both
  removed for the same reason: a standalone promotion is just another MCP
  tool name the Claude CLI can lose track of across its per-turn tool
  re-handshake (FR a435605d — client-side, not a server bug), and with only
  `run_elixir` left that failure mode is gone by construction.

    * `search_tools` (a ranked keyword search meta-tool) — its job is fully
      covered by the already-existing `Tools.search/1` (generated by
      `OrcaHub.MCP.CodeExec.ToolGen`, independent of this module), so it was
      pure duplication once promotion stopped being a reason to keep a
      second, MCP-level copy of the same search.
    * The `@passthrough_tool_names` promotions (`send_message_to_session`,
      `get_session_tail`, `report_progress`, and the feature-request tools) —
      previously exposed as standalone tools alongside the meta-tools because
      orchestrator/code-exec sessions called them so frequently that
      round-tripping through `run_elixir` felt like overhead. They're called
      as ordinary `Tools.*` functions now, same as everything else.

  A third meta-tool, `read_tool` (single-tool schema lookup by raw MCP name),
  was removed earlier for the same reason `search_tools` just was: production
  usage showed it was the weakest of the three (27 calls across 15 sessions
  vs. 589 across 70 for `run_elixir`) and its job is fully covered by
  `Tools.schema/1` inside `run_elixir`. Old sessions may still have persisted
  `read_tool` calls in their message history — `MessageComponents` keeps a
  render clause for those — but it's no longer callable. The same applies to
  `search_tools` and the passthrough tool names now: history keeps rendering
  fine, they're just not callable going forward.

  `run_elixir`'s tool definition is built **at call time**, not a compile-time
  `@tools` attribute, so its description can list the CURRENT first-party
  tool names (`OrcaHub.MCP.Tools.list/0`) and connected upstream server
  prefixes (`OrcaHub.MCP.UpstreamClient.prefixes/0`) — both of which change at
  runtime — without risking the list drifting from a hand-maintained literal.

  `run_elixir`'s result text distinguishes **rejected before running** (syntax
  error / allowlist violation — the model should fix its code) from **ran and
  failed** (`Tools.Error`, another exception, or a timeout — a tool/expression
  outcome).

  Variables assigned in `run_elixir` persist across calls within the same
  session (see `OrcaHub.MCP.CodeExec.BindingStore`). A raise still persists
  whatever earlier top-level statements in the snippet successfully bound
  (see `OrcaHub.MCP.CodeExec.Sandbox`'s sequential top-level evaluation);
  `"reset": true` clears the stored binding entirely.
  """

  alias OrcaHub.MCP.CodeExec
  alias OrcaHub.MCP.Tools.Result
  alias OrcaHub.MCP.UpstreamClient

  @meta_tool_names ~w(run_elixir)

  @doc "The collapsed tool definitions shown to a code-exec connection: just run_elixir."
  def list, do: [run_elixir_tool()]

  @doc "True if `name` is the run_elixir meta-tool."
  def meta_tool?(name), do: name in @meta_tool_names

  @doc """
  Dispatch a meta-tool call. `state` is the MCP server state, threaded into
  evaluated code so `Tools.*` calls run with the connection's identity.
  """
  def call("run_elixir", args, state), do: run_elixir(args, state)

  def call(name, _args, _state) do
    Result.error(
      "Unknown tool: #{name}. In code-exec mode this connection exposes only " <>
        "run_elixir; call other tools as Tools.<name> inside run_elixir " <>
        "(use Tools.schema(\"name\") or Tools.search(\"query\") there to find a tool " <>
        "and its input schema)."
    )
  end

  # ── tool definitions (built at call time — see moduledoc) ────────────

  defp run_elixir_tool do
    %{
      "name" => "run_elixir",
      "description" => run_elixir_description(),
      "inputSchema" => %{
        "type" => "object",
        "properties" => %{
          "code" => %{"type" => "string", "description" => "Elixir code to evaluate."},
          "reset" => %{
            "type" => "boolean",
            "description" =>
              "If true, clear this session's persisted variables before evaluating " <>
                "(the snippet then runs with a fresh binding)."
          }
        },
        "required" => ["code"]
      }
    }
  end

  defp run_elixir_description do
    """
    Evaluate Elixir code that can call OrcaHub + upstream MCP tools as named \
    functions and combine their results with the standard library. This is \
    the ONLY MCP tool this connection exposes — every OrcaHub coordination \
    tool and every upstream tool is reachable ONLY as a `Tools.*` function \
    called from here, never as a standalone tool. Prefer writing one snippet \
    that calls several tools over many separate `run_elixir` calls: return \
    only the slim value you need.

    Tools are exposed as `Tools.*` functions that AUTO-UNWRAP the result and \
    RAISE `Tools.Error` on failure, so they compose with `|>` and `Enum`:

        Tools.github__list_issues(%{"repo" => "o/r"})
        |> Enum.filter(& &1["state"] == "open")
        |> Enum.map(& &1["title"])

    Discover tools from inside code with `Tools.search("query")`, \
    `Tools.list()`, and `Tools.schema("name")` — the tool's JSON input schema, \
    worth checking before calling an unfamiliar tool. For example, \
    `Tools.search("discord")` surfaces `Tools.send_discord_message` if a \
    Discord upstream is connected. `search`/`list` return maps with \
    "name"/"description" keys (search results also include "args" — a list of \
    argument names, with optional ones suffixed "?", e.g. ["repo", \
    "number?"]); `schema` returns a map (or `nil`). For explicit error \
    handling use `Tools.try_call("name", args)` -> `{:ok, value} | {:error, reason}`, \
    or `Tools.call("name", args)` for the faithful MCP envelope. Pure stdlib \
    (Enum, Map, String, Jason, ...) is available; OrcaHub internals, File, \
    System, and process/dispatch primitives are blocked. The returned value of \
    the last expression and any stdout are sent back — keep it slim: \
    filter/project before returning.

    Tools you'll likely call often, all as `Tools.<name>(args)` from here:

        Tools.send_message_to_session(%{"session_id" => "...", "message" => "..."})
        Tools.get_session_tail(%{"session_id" => "..."})
        Tools.report_progress(%{"phase" => "implementing", "note" => "..."})
        # orchestrator flows:
        Tools.start_session(%{"directory" => "...", "prompt" => "..."})
        Tools.search_sessions(%{"status" => "error"})
        Tools.schedule_heartbeat(%{"interval_seconds" => 300, "message" => "..."})
        # feature-request backlog:
        Tools.file_feature_request(%{"title" => "...", "description" => "..."})
        Tools.list_feature_requests(%{})

    First-party OrcaHub tools available as Tools.* in every session: \
    #{first_party_tool_names()}. #{upstream_prefixes_line()}

    Variables you bind PERSIST across run_elixir calls within this session, \
    like a REPL: fetch data once into a variable, then slice/reshape it in \
    later calls instead of re-fetching.

        sessions = Tools.search_sessions(%{"status" => "error"})
        # ...next call...
        Enum.map(sessions, & &1["title"])

    Pass `"reset": true` to clear your session's stored variables and start \
    fresh (the snippet then runs against an empty binding).\
    """
  end

  defp first_party_tool_names do
    OrcaHub.MCP.Tools.list()
    |> Enum.map(& &1["name"])
    |> Enum.sort()
    |> Enum.join(", ")
  end

  defp upstream_prefixes_line do
    case UpstreamClient.prefixes() do
      [] ->
        "No upstream MCP servers are currently connected."

      prefixes ->
        "Connected upstream MCP servers: #{Enum.join(Enum.sort(prefixes), ", ")} — their " <>
          "tools are namespaced <prefix>__<tool> and searchable via Tools.search."
    end
  end

  # ── run_elixir ───────────────────────────────────────────────────────

  defp run_elixir(%{"code" => code} = args, state) when is_binary(code) do
    reset? = args["reset"] == true

    case CodeExec.run(code, state, reset: reset?) do
      {:ok, %{value: value, stdout: stdout} = result} ->
        Result.text(format_success(value, stdout, Map.get(result, :note)))

      {:error, {:rejected, reason}} ->
        Result.error("Code rejected before running (fix your code): #{reason}")

      {:error, {:timeout, ms}} ->
        Result.error("Code ran but was killed after exceeding the #{ms}ms time limit.")

      {:error, {:exception, %{banner: banner, line: line, stdout: stdout} = info}} ->
        Result.error(format_exception(banner, line, stdout, Map.get(info, :note)))
    end
  end

  defp run_elixir(_args, _state),
    do: Result.error("run_elixir requires a `code` string argument.")

  # Same budget the sandbox caps stdout/exception banners at (see Sandbox's
  # @default_max_output) — the returned value gets no cap otherwise, and a big
  # tool result would be a context bomb.
  @max_value_bytes 50_000

  defp format_success(value, stdout, note) do
    out = if stdout == "", do: "", else: "stdout:\n#{stdout}\n"
    note_line = if note, do: "\n\n#{note}", else: ""
    "#{out}=> #{cap_value(inspect(value, pretty: true, limit: :infinity))}#{note_line}"
  end

  defp cap_value(formatted) when byte_size(formatted) > @max_value_bytes do
    truncated = byte_size(formatted) - @max_value_bytes

    binary_part(formatted, 0, @max_value_bytes) <>
      "\n…[truncated #{truncated} bytes — filter/project the value in your code before returning it]"
  end

  defp cap_value(formatted), do: formatted

  defp format_exception(banner, line, stdout, note) do
    where = if line, do: " (at line #{line})", else: ""
    out = if stdout == "", do: "", else: "stdout before failure:\n#{stdout}\n"
    note_line = if note, do: "\n\n#{note}", else: ""
    "#{out}Code ran but raised#{where}:\n#{banner}#{note_line}"
  end
end
