defmodule OrcaHub.Cluster.HotLoadGate do
  @moduledoc """
  Decides whether a source diff is safe to ship by BEAM hot code loading
  (`OrcaHub.Cluster.CodeSync` pushing recompiled `.beam` files onto the
  running nodes) instead of by a full release build + restart.

  This module is PURE: it takes a description of what changed and returns a
  verdict. It never shells out, never reads the filesystem, and never talks
  to a node. `OrcaHub.Cluster.HotLoadGate.GitDiff` is the (impure, untested)
  helper that turns a git ref into the input shape this module wants.

  ## Why a gate exists at all

  A full deploy of OrcaHub is a multi-minute multi-arch Docker build plus a
  restart of six instances, and every restart kills in-flight sessions. Hot
  loading the same change takes seconds and disturbs nothing. The catch is
  that the changes which are NOT safe to hot-load fail *silently* — the push
  succeeds, the nodes keep running, and the damage shows up later as a
  crashed GenServer, a stale `/api/version`, or config that mysteriously
  never took effect. Nobody gets an error at push time telling them they
  chose the wrong deploy mechanism. This gate is that error.

  Every rule here is "refuse if unsure". A false refusal costs one slow
  deploy; a false allow costs a silent production defect that is hard to
  attribute back to the push that caused it.

  ## The `defstruct` rule (category 7) — read this before deleting it

  This is the subtle one, and the main reason the gate is worth having.

  Hot code loading swaps the CODE of a module. It does not touch the TERMS
  that already exist in running processes' state. A long-lived GenServer
  holding `%State{a: 1}` keeps exactly that two-key map (`:__struct__` and
  `:a`) across the load. If the new code adds field `b`, then on the very
  next message the new function clauses pattern-match, or `Map.fetch!`, or
  `%{state | b: ...}` against a shape that is **not there**, and the process
  crashes with a `KeyError`/`FunctionClauseError`.

  The supervisor then restarts it with a correctly-shaped fresh state, so
  the system "heals" — which is precisely what makes this dangerous. The
  fleet looks fine afterwards. What is gone is whatever that process was
  holding: for OrcaHub that can be a mid-turn session's runner state, a
  warm port, a pending queue. The blast radius is invisible in any health
  check you would think to run after a push.

  The correct way to ship a struct change to a running node is an OTP
  release upgrade with a `code_change/3` callback that migrates the old term
  — which is exactly what we are not doing when we push bare beams. So: any
  added, removed or modified `defstruct` line in any module refuses.

  Known gap, deliberate: a struct generated by a macro rather than a literal
  `defstruct` line — most importantly an Ecto `schema do ... end` block —
  has the same hazard and is NOT detected. Detecting it reliably means
  understanding the macro, not grepping a diff. Ecto schema structs are in
  practice short-lived request/query terms rather than long-lived process
  state, which is why this is a documented gap rather than a blocker; if
  that stops being true, this is the first rule to extend.

  ## Why the default is ALLOW

  Anything not matched by a rule below is hot-loadable. That is a decision,
  not an oversight, and it rests on what hot loading actually does: replace
  a module's code. For the overwhelming bulk of this codebase — a changed
  function body, a new function, a fixed guard, a `.heex` template (compiled
  into its view module), a new module entirely — replacing the code IS the
  whole change. There is no other state to migrate.

  The refuse list is therefore an enumeration of the specific ways a change
  reaches *beyond* module code: into the dependency set, into compile-time
  config, into the database schema, into the browser, into process state
  shape, into the supervision structure, or into the release/runtime
  plumbing. If a future category is discovered, the fix is to add it here
  with its reasoning, not to invert the default.

  Two further known gaps, both deliberate and both listed so the next reader
  does not mistake them for oversights:

    * A **deleted** `lib/**.ex` file is classified by its content rules
      only. Hot loading cannot un-load a module on a remote node, so the
      deleted module stays resident and callable there. This is usually
      harmless (nothing calls it) but it is not nothing.
    * A changed module attribute that other modules read at COMPILE time
      (a `@behaviour` callback list, a shared `@constant` consumed via a
      macro) needs its *consumers* recompiled and pushed too. This gate
      sees the changed file, not its compile-time dependents; the push side
      should push a full recompile, not a hand-picked module list.

  ## Input

  `classify/2` takes a list of changes. Each change may be:

    * `"lib/orca_hub/foo.ex"` — a bare repo-relative path, no diff content
    * `{"lib/orca_hub/foo.ex", diff_text}` — path plus unified diff text
    * `%{path: p, diff: diff_text, status: :added | :modified | :deleted}`

  Categories 6 (supervision tree) and 7 (`defstruct`) need the diff body,
  not just the path. A change to an `.ex`/`.exs` file that arrives with no
  diff text is therefore refused as `:missing_diff` rather than waved
  through — an unreadable change is an unverified change. Pass
  `require_diff: false` to downgrade that to path-only classification, and
  understand that doing so disables categories 6 and 7 for those files.

  ## Output

      {:ok, :hot_loadable}     # nothing matched; push it
      {:refuse, [%Reason{}]}   # at least one rule matched
      {:forced, [%Reason{}]}   # rules matched but opts[:force] was set

  The forced verdict still carries every reason, so a caller can log exactly
  what was overridden. Reasons are never silently dropped.

  ## Example

      iex> alias OrcaHub.Cluster.HotLoadGate
      iex> HotLoadGate.classify([{"lib/orca_hub/sessions.ex", "@@ -1,2 +1,2 @@\\n-  def a, do: 1\\n+  def a, do: 2\\n"}])
      {:ok, :hot_loadable}

      iex> alias OrcaHub.Cluster.HotLoadGate
      iex> {:refuse, [reason]} = HotLoadGate.classify(["mix.lock"])
      iex> reason.category
      :dependency_change
  """

  alias OrcaHub.Cluster.HotLoadGate.Reason

  @typedoc "A repo-relative path, optionally paired with its unified diff text."
  @type change ::
          String.t()
          | {String.t(), String.t() | nil}
          | %{
              required(:path) => String.t(),
              optional(:diff) => String.t() | nil,
              optional(:status) => status
            }

  @type status :: :added | :modified | :deleted | :unknown

  @type verdict ::
          {:ok, :hot_loadable}
          | {:refuse, [Reason.t()]}
          | {:forced, [Reason.t()]}

  # Stable output order. Reasons are grouped by category in this order, and
  # by path within a category, so an operator (and a test) sees the same
  # list for the same diff every time.
  @category_order [
    :dependency_change,
    :build_config,
    :app_config,
    :migration,
    :frontend_asset,
    :supervision_tree,
    :defstruct_change,
    :build_info,
    :release_plumbing,
    :missing_diff
  ]

  @application_path "lib/orca_hub/application.ex"
  @build_info_path "lib/orca_hub/build_info.ex"

  # Lines whose addition or removal means the supervision structure moved.
  # Matched against the diff line with its leading +/- stripped.
  @supervision_patterns [
    {~r/\bchild_spec\b/, "child_spec"},
    {~r/\bSupervisor\.init\b/, "Supervisor.init"},
    {~r/\bSupervisor\.start_link\b/, "Supervisor.start_link"},
    {~r/\bDynamicSupervisor\.(init|start_link)\b/, "DynamicSupervisor init/start_link"},
    {~r/\bPartitionSupervisor\.(init|start_link)\b/, "PartitionSupervisor init/start_link"},
    {~r/^\s*children\s*=/, "supervisor children list"},
    {~r/\buse\s+(Dynamic|Partition)?Supervisor\b/, "use Supervisor"}
  ]

  @defstruct_pattern ~r/^\s*defstruct\b/

  # -------------------------------------------------------------------
  # Public API
  # -------------------------------------------------------------------

  @doc """
  Classify a list of changes as hot-loadable or not.

  ## Options

    * `:force` (boolean, default `false`) — return `{:forced, reasons}`
      instead of `{:refuse, reasons}` when rules match. The reasons are
      still returned in full so the caller can log the override.
    * `:require_diff` (boolean, default `true`) — refuse `.ex`/`.exs`
      changes that arrive without diff text. Setting this to `false`
      disables the supervision-tree and `defstruct` checks for those files.
  """
  @spec classify([change], keyword) :: verdict
  def classify(changes, opts \\ []) when is_list(changes) and is_list(opts) do
    force? = Keyword.get(opts, :force, false)
    require_diff? = Keyword.get(opts, :require_diff, true)

    reasons =
      changes
      |> Enum.map(&normalize/1)
      |> Enum.flat_map(&reasons_for(&1, require_diff?))
      |> sort_reasons()

    cond do
      reasons == [] -> {:ok, :hot_loadable}
      force? -> {:forced, reasons}
      true -> {:refuse, reasons}
    end
  end

  @doc """
  Render a verdict (or a bare reason list) as a short operator-facing string.

  The audience is someone deciding whether to override, so each line says
  what changed, which rule it hit, and what actually goes wrong if it is
  hot-loaded anyway.
  """
  @spec explain(verdict | [Reason.t()]) :: String.t()
  def explain({:ok, :hot_loadable}), do: "Hot-loadable: no blocking changes found."

  def explain({:refuse, reasons}) do
    header(reasons, "REFUSED") <> body(reasons) <> footer()
  end

  def explain({:forced, reasons}) do
    header(reasons, "OVERRIDDEN (force: true)") <>
      body(reasons) <>
      "\nThese were overridden, not resolved. A full deploy is the safe path.\n"
  end

  def explain(reasons) when is_list(reasons),
    do: header(reasons, "REFUSED") <> body(reasons) <> footer()

  @doc """
  `true` when the verdict permits a push — i.e. clean, or explicitly forced.

  Deliberately does not take `opts`: a caller must have gone through
  `classify/2` (and therefore have the reasons in hand) to get here.
  """
  @spec hot_loadable?(verdict) :: boolean
  def hot_loadable?({:ok, :hot_loadable}), do: true
  def hot_loadable?({:forced, _reasons}), do: true
  def hot_loadable?({:refuse, _reasons}), do: false

  @doc "The reasons carried by a verdict; `[]` for a clean one."
  @spec reasons(verdict) :: [Reason.t()]
  def reasons({:ok, :hot_loadable}), do: []
  def reasons({:refuse, reasons}), do: reasons
  def reasons({:forced, reasons}), do: reasons

  @doc "Every refuse category this gate can emit, in report order."
  @spec categories() :: [atom]
  def categories, do: @category_order

  # -------------------------------------------------------------------
  # Normalization
  # -------------------------------------------------------------------

  defp normalize(path) when is_binary(path),
    do: %{path: clean_path(path), diff: nil, status: :unknown}

  defp normalize({path, diff}) when is_binary(path),
    do: %{path: clean_path(path), diff: diff, status: :unknown}

  defp normalize(%{path: path} = change) when is_binary(path) do
    %{
      path: clean_path(path),
      diff: Map.get(change, :diff),
      status: Map.get(change, :status, :unknown)
    }
  end

  # Paths are expected repo-relative; tolerate the "./" a caller may prepend.
  defp clean_path(path) do
    path
    |> String.trim()
    |> String.replace_leading("./", "")
  end

  # -------------------------------------------------------------------
  # Rules
  # -------------------------------------------------------------------

  defp reasons_for(change, require_diff?) do
    path_reasons = path_reasons(change)
    content_reasons = content_reasons(change)

    # A path rule and a content rule can land on the same category for the
    # same file — lib/orca_hub/application.ex both IS the supervision tree
    # and contains `children = [`. Keep the path-based one: it comes first
    # here and its message is the more specific of the two.
    found = Enum.uniq_by(path_reasons ++ content_reasons, &{&1.category, &1.path})

    cond do
      found != [] ->
        found

      require_diff? and needs_diff?(change) and is_nil(change.diff) ->
        [missing_diff_reason(change)]

      true ->
        []
    end
  end

  defp path_reasons(%{path: path} = change) do
    segments = Path.split(path)
    basename = Path.basename(path)

    [
      path == "mix.lock" && dependency_change(change),
      path == "mix.exs" && build_config(change),
      config_exs?(segments, path) && app_config(change),
      migration?(path) && migration(change),
      frontend?(path) && frontend_asset(change),
      path == @application_path && supervision_tree_by_path(change),
      path == @build_info_path && build_info(change),
      release_plumbing?(path, basename) && release_plumbing(change)
    ]
    |> Enum.filter(& &1)
  end

  defp config_exs?(segments, path),
    do: hd(segments) == "config" and String.ends_with?(path, ".exs")

  defp migration?(path), do: String.starts_with?(path, "priv/repo/migrations/")

  defp frontend?(path),
    do: String.starts_with?(path, "assets/") or String.starts_with?(path, "priv/static/")

  defp release_plumbing?(path, basename) do
    String.starts_with?(path, "rel/") or
      String.starts_with?(path, "systemd/") or
      basename == "Dockerfile" or
      String.starts_with?(basename, "Dockerfile.")
  end

  # Source files whose *content* decides the verdict. A `.heex` template is
  # compiled into its view module and carries neither a defstruct nor a
  # supervision tree, so it does not need its diff read.
  defp needs_diff?(%{path: path}),
    do: String.ends_with?(path, ".ex") or String.ends_with?(path, ".exs")

  defp content_reasons(%{diff: nil}), do: []

  defp content_reasons(%{diff: diff} = change) when is_binary(diff) do
    hunks = diff_hunks(diff)

    changed = Enum.flat_map(hunks, &changed_in_hunk/1)

    direct_hits =
      for line <- changed,
          {regex, label} <- @supervision_patterns,
          Regex.match?(regex, line),
          do: {label, line}

    supervision_hits = direct_hits ++ Enum.flat_map(hunks, &children_region_hits/1)
    defstruct_hits = Enum.filter(changed, &Regex.match?(@defstruct_pattern, &1))

    []
    |> append_if(supervision_hits != [], fn ->
      supervision_tree_by_diff(change, supervision_hits)
    end)
    |> append_if(defstruct_hits != [], fn -> defstruct_change(change, defstruct_hits) end)
  end

  defp append_if(list, false, _fun), do: list
  defp append_if(list, true, fun), do: list ++ [fun.()]

  @doc false
  # Added/removed lines of a unified diff, with the +/- marker stripped.
  #
  # `--- `/`+++ ` file headers are excluded (they are not content), and so is
  # the `@@` hunk header: git puts the enclosing function's source line in
  # its trailing context, so a hunk inside a struct module reads
  # `@@ -10,6 +10,7 @@ defstruct [:a]` and would otherwise match every
  # pattern here on an unrelated edit.
  #
  # Plain (headerless) diff bodies are accepted too, so a caller can hand in
  # just the hunk lines.
  def changed_lines(diff) when is_binary(diff) do
    diff |> diff_hunks() |> Enum.flat_map(&changed_in_hunk/1)
  end

  # Diff body split into hunks, each a list of raw (marker-carrying) lines.
  # Hunks are separate scanning units because they are discontinuous regions
  # of the file — bracket depth cannot be carried across a `@@` boundary.
  defp diff_hunks(diff) do
    diff
    |> String.split("\n")
    |> Enum.reject(&file_header?/1)
    |> Enum.reduce([[]], fn line, [current | rest] ->
      if String.starts_with?(line, "@@"),
        do: [[] | [Enum.reverse(current) | rest]],
        else: [[line | current] | rest]
    end)
    |> then(fn [current | rest] -> Enum.reverse([Enum.reverse(current) | rest]) end)
  end

  # `--- a/mix.exs`, not a removed source line. Requiring whitespace after the
  # three markers keeps a removed `---- section ----` from being swallowed.
  defp file_header?(line) do
    Regex.match?(~r/^(---|\+\+\+)(\s|$)/, line) or
      String.starts_with?(line, "diff --git ") or
      String.starts_with?(line, "index ") or
      String.starts_with?(line, "new file mode ") or
      String.starts_with?(line, "deleted file mode ")
  end

  defp changed_in_hunk(lines) do
    for line <- lines, {marker, content} = split_marker(line), marker != :context, do: content
  end

  defp split_marker("+" <> rest), do: {:add, rest}
  defp split_marker("-" <> rest), do: {:del, rest}
  defp split_marker(" " <> rest), do: {:context, rest}
  defp split_marker(line), do: {:context, line}

  # The case the direct patterns miss, and the one that actually happens:
  # a child was added to or removed from an existing `children = [...]` list,
  # so the only changed line is the child entry itself — the `children = [`
  # line is unchanged CONTEXT. Track square-bracket depth through the hunk
  # and flag any changed line sitting inside such a list.
  #
  # Limitation, worth knowing before trusting a clean verdict: this only sees
  # what the diff's context window shows. A child edited far enough from its
  # `children = [` opener that the opener is not in the hunk is invisible
  # here, which is why `GitDiff` asks git for a generous context window.
  defp children_region_hits(lines) do
    {hits, _depth} =
      Enum.reduce(lines, {[], 0}, fn line, {hits, depth} ->
        {marker, content} = split_marker(line)

        depth_after =
          cond do
            depth > 0 -> max(depth + bracket_delta(content), 0)
            children_list_opener?(content) -> max(bracket_delta(content), 0)
            true -> 0
          end

        inside? = depth > 0 or depth_after > 0

        if marker != :context and inside? do
          {[{"supervisor children list", content} | hits], depth_after}
        else
          {hits, depth_after}
        end
      end)

    Enum.reverse(hits)
  end

  defp children_list_opener?(content) do
    Regex.match?(~r/\bchildren\s*=\s*\[/, content) or
      Regex.match?(~r/^\s*@children\s+\[/, content)
  end

  defp bracket_delta(content) do
    count(content, "[") - count(content, "]")
  end

  defp count(string, char), do: string |> String.graphemes() |> Enum.count(&(&1 == char))

  # -------------------------------------------------------------------
  # Reason constructors — the operator-facing text lives here
  # -------------------------------------------------------------------

  defp dependency_change(change) do
    reason(change, :dependency_change, """
    Dependency versions changed. Hot loading pushes only :orca_hub's own beams; \
    a new or upgraded dependency's modules are not in the running node's code path \
    at all, so the first call into one fails with :undef (or silently keeps running \
    the OLD version, which is worse). Needs a full build.\
    """)
  end

  defp build_config(change) do
    reason(change, :build_config, """
    mix.exs changed. It defines application/0 (the boot-time supervision entry \
    point), extra_applications, the dep list and compile-time elixirc options — \
    none of which a beam push can update on a node that is already running. \
    This gate deliberately does NOT try to work out which part of mix.exs moved; \
    every change refuses. Needs a full build.\
    """)
  end

  defp app_config(change) do
    reason(change, :app_config, """
    Config changed. Compile-time config (config/config.exs and friends, read via \
    Application.compile_env) is baked into the beams of every module that reads \
    it, so pushing only the changed file's beam leaves those consumers stale. \
    runtime.exs is no better: it is evaluated once during boot, so a running node \
    never re-reads it. Needs a restart.\
    """)
  end

  defp migration(change) do
    reason(change, :migration, """
    Database migration changed. Hot loading runs no migrations, so the new code \
    would execute against the old schema — queries referencing a column that does \
    not exist yet fail at the database, per-request, with no hint that a deploy \
    step was skipped. Needs a real deploy (and its migration step).\
    """)
  end

  defp frontend_asset(change) do
    reason(change, :frontend_asset, """
    Browser-side asset changed. Hot loading replaces BEAM modules only; it does \
    not run esbuild/tailwind and does not update priv/static or the asset digest \
    manifest. Connected browsers keep the old JS/CSS, and the served bundle stays \
    whatever the last real build produced. Needs a full build.\
    """)
  end

  defp supervision_tree_by_path(change) do
    reason(change, :supervision_tree, """
    #{@application_path} defines the boot-time supervision tree. Its start/2 has \
    already run on every live node, so a pushed beam changes what WOULD be started \
    on the next boot and nothing about what is running now: added children never \
    start, removed children keep running, and changed start args/strategy do not \
    apply. The node then looks healthy while diverging from its own source. \
    Needs a restart.\
    """)
  end

  defp supervision_tree_by_diff(change, hits) do
    labels = hits |> Enum.map(&elem(&1, 0)) |> Enum.uniq() |> Enum.join(", ")

    reason(
      change,
      :supervision_tree,
      """
      Supervision structure changed (#{labels}). A supervisor's children are read \
      from init/1 when the supervisor STARTS; a running one keeps the child list it \
      already has. So a pushed beam adds no child, removes no child, and changes no \
      restart strategy on a live node — the code and the running tree silently \
      disagree until the next restart.\
      """,
      hits |> Enum.map(&elem(&1, 1)) |> evidence()
    )
  end

  defp defstruct_change(change, hits) do
    reason(
      change,
      :defstruct_change,
      """
      defstruct changed. Hot loading swaps code but NOT the terms already held in \
      running processes: a GenServer holding the old %State{} keeps the old key set \
      forever. New code matching on a field the live term does not have crashes on \
      the next message, and the supervisor restarts it with a correct shape — so it \
      self-heals NOISILY, destroying whatever that process held (for OrcaHub that \
      can be a mid-turn session). Migrating an existing term needs a release upgrade \
      with code_change/3, which a beam push is not.\
      """,
      evidence(hits)
    )
  end

  defp build_info(change) do
    reason(change, :build_info, """
    #{@build_info_path} resolves @sha and @built_at at COMPILE time from the \
    compiling machine's git state. Pushing this module makes every node report the \
    COMPILING host's HEAD from /api/version — i.e. the one endpoint used to verify a \
    deploy would start lying, claiming a SHA the fleet is not running. This module \
    should also be excluded from the push payload itself, not merely refused here.\
    """)
  end

  defp release_plumbing(change) do
    reason(change, :release_plumbing, """
    Release/runtime plumbing changed (rel/, Dockerfile, systemd/). None of it is \
    BEAM code: it shapes the image, the vm.args, the release env and the service \
    unit, all of which are consumed at build or boot time. A beam push cannot \
    deliver any of it. Needs a full deploy.\
    """)
  end

  defp missing_diff_reason(change) do
    reason(change, :missing_diff, """
    No diff content supplied for an Elixir source file, so the defstruct and \
    supervision-tree checks could not run on it. An unread change is an unverified \
    change; this gate refuses rather than guessing. Supply the diff text, or pass \
    require_diff: false to accept path-only classification (which disables those \
    two checks).\
    """)
  end

  defp reason(change, category, message, evidence \\ []) do
    %Reason{
      category: category,
      path: change.path,
      status: change.status,
      message: String.trim(message),
      evidence: evidence
    }
  end

  # Keep the rendered output short: a couple of representative lines beat a
  # full hunk when the reader is deciding go/no-go.
  defp evidence(lines) do
    lines
    |> Enum.map(&String.trim/1)
    |> Enum.uniq()
    |> Enum.take(3)
  end

  # -------------------------------------------------------------------
  # Rendering
  # -------------------------------------------------------------------

  defp sort_reasons(reasons) do
    Enum.sort_by(reasons, fn r ->
      {Enum.find_index(@category_order, &(&1 == r.category)) || 99, r.path}
    end)
  end

  defp header(reasons, verb) do
    n = length(reasons)
    files = reasons |> Enum.map(& &1.path) |> Enum.uniq() |> length()

    "Hot load #{verb}: #{n} blocking change#{plural(n)} across #{files} file#{plural(files)}.\n\n"
  end

  defp plural(1), do: ""
  defp plural(_), do: "s"

  defp body(reasons) do
    reasons
    |> Enum.map_join("\n", fn r ->
      "  [#{r.category}] #{r.path}\n" <>
        indent(r.message) <>
        evidence_block(r.evidence)
    end)
  end

  defp evidence_block([]), do: ""

  defp evidence_block(evidence) do
    Enum.map_join(evidence, "", fn line -> "      > #{line}\n" end)
  end

  defp indent(message) do
    message
    |> String.split("\n")
    |> Enum.map_join("", fn line -> "    #{line}\n" end)
  end

  defp footer do
    "\nOverride with force: true only if you have confirmed the above does not " <>
      "apply.\nOtherwise run a full deploy.\n"
  end
end
