defmodule OrcaHubWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :orca_hub

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_orca_hub_key",
    signing_salt: "fHvMs9MO",
    same_site: "Lax"
  ]

  # Agent nodes are supposed to serve ONLY the MCP HTTP endpoint — no web UI,
  # no webhooks, no Agent Runs API, no terminals. This runs before anything
  # else in the pipeline (including Plug.Static) so it also blocks static
  # assets in agent mode. `OrcaHub.Mode.agent?/0` is checked at request time
  # (runtime config), not baked in at compile time.
  #
  # Caveat: Phoenix's own `:socket_dispatch` plug (injected unconditionally by
  # `use Phoenix.Endpoint`, ahead of any plug declared in this module) still
  # owns the literal "/live/websocket", "/live/longpoll", and
  # "/terminal_socket/websocket" paths — this gate can't intercept those
  # before Phoenix's socket transport code runs. That's fine in practice:
  # those transports require a signed session token minted by an initial page
  # load, and this gate 404s every page route, so there's never a valid token
  # for an attacker to present.
  plug :agent_mode_gate

  socket "/terminal_socket", OrcaHubWeb.UserSocket, websocket: true

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :orca_hub,
    gzip: not code_reloading?,
    only: OrcaHubWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :orca_hub
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  plug :healthz
  plug :version

  plug Plug.Session, @session_options
  plug OrcaHubWeb.Router

  defp healthz(%{request_path: "/healthz"} = conn, _opts) do
    conn
    |> Plug.Conn.send_resp(200, "ok")
    |> Plug.Conn.halt()
  end

  defp healthz(conn, _opts), do: conn

  # Unauthenticated on purpose (like /healthz above): a git SHA of a
  # private repo is low-sensitivity, and the deploy script needs to poll
  # this from plain localhost/cluster HTTP without minting a bearer token.
  # Handled directly in the endpoint, ahead of the session/router pipeline,
  # so it works identically for the local systemd, mini, and k8s instances.
  defp version(%{request_path: "/api/version"} = conn, _opts) do
    body = Jason.encode!(%{sha: OrcaHub.BuildInfo.sha(), built_at: OrcaHub.BuildInfo.built_at()})

    conn
    |> Plug.Conn.put_resp_content_type("application/json")
    |> Plug.Conn.send_resp(200, body)
    |> Plug.Conn.halt()
  end

  defp version(conn, _opts), do: conn

  defp agent_mode_gate(conn, _opts) do
    if OrcaHub.Mode.agent?() and not agent_mode_allowed?(conn.path_info) do
      conn
      |> Plug.Conn.put_resp_content_type("text/plain")
      |> Plug.Conn.send_resp(404, "not found")
      |> Plug.Conn.halt()
    else
      conn
    end
  end

  # MCP Streamable HTTP endpoint (and any subpaths under it).
  defp agent_mode_allowed?(["mcp" | _]), do: true
  # k8s liveness/readiness probes.
  defp agent_mode_allowed?(["healthz"]), do: true
  # Deploy script polls this over plain HTTP; see `version/2` above.
  defp agent_mode_allowed?(["api", "version"]), do: true
  defp agent_mode_allowed?(_path_info), do: false
end
