defmodule OrcaHubWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :orca_hub

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_orca_hub_key",
    signing_salt: "fHvMs9MO",
    same_site: "Lax"
  ]

  # Agent nodes are supposed to serve ONLY the MCP HTTP endpoint — no web UI,
  # no webhooks, no Agent Runs API, no terminals. This runs before anything
  # else in the pipeline (including Plug.Static) so it also blocks static
  # assets in agent mode. `OrcaHub.Mode.agent?/0` is checked at request time
  # (runtime config), not baked in at compile time.
  #
  # Caveat: Phoenix's own `:socket_dispatch` plug (injected unconditionally by
  # `use Phoenix.Endpoint`, ahead of any plug declared in this module) still
  # owns the literal "/live/websocket", "/live/longpoll", and
  # "/terminal_socket/websocket" paths — this gate can't intercept those
  # before Phoenix's socket transport code runs. That's fine in practice:
  # those transports require a signed session token minted by an initial page
  # load, and this gate 404s every page route, so there's never a valid token
  # for an attacker to present.
  plug :agent_mode_gate

  socket "/terminal_socket", OrcaHubWeb.UserSocket, websocket: true

  # The API push socket (session turn-end events). Token-authenticated in
  # `OrcaHubWeb.ApiSocket.connect/3` — including its own agent-mode refusal,
  # since the caveat above means `agent_mode_gate` never sees this path.
  # WebSocket only: the client is a long-lived Android foreground service,
  # and longpoll would buy it nothing but a second auth surface.
  socket "/api/v1/socket", OrcaHubWeb.ApiSocket, websocket: true, longpoll: false

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :orca_hub,
    gzip: not code_reloading?,
    only: OrcaHubWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :orca_hub
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head

  plug :healthz
  plug :version
  plug :drain

  plug Plug.Session, @session_options
  plug OrcaHubWeb.Router

  defp healthz(%{request_path: "/healthz"} = conn, _opts) do
    conn
    |> Plug.Conn.send_resp(200, "ok")
    |> Plug.Conn.halt()
  end

  defp healthz(conn, _opts), do: conn

  # Unauthenticated on purpose (like /healthz above): a git SHA of a
  # private repo is low-sensitivity, and the deploy script needs to poll
  # this from plain localhost/cluster HTTP without minting a bearer token.
  # Handled directly in the endpoint, ahead of the session/router pipeline,
  # so it works identically for the local systemd, mini, and k8s instances.
  #
  # TWO shas, and they answer different questions:
  #
  #   * `sha`/`built_at` — the IMAGE this node booted from, compile-time
  #     attributes of `OrcaHub.BuildInfo` (a module that is deliberately
  #     never hot-pushed). deploy-orca-hub.sh and verify-orca-deploy.sh both
  #     parse `sha` with `grep -o '"sha":"[^"]*"'` and gate on it, so its
  #     name, shape and meaning are frozen — and note no other key here may
  #     END in a bare `"sha":"`, which is why the live one is `code_sha`.
  #   * `code_sha` — the generation currently APPLIED here, from
  #     `OrcaHub.Cluster.CodeStamp`. Once a node has been hot-loaded this is
  #     the only field describing the code it is actually running.
  #
  # `code_sha` is `null`, and `code.source` is `"image"`, when no generation
  # has been applied. It deliberately does NOT fall back to echoing `sha`:
  # the entire point of the field is to distinguish "running its image" from
  # "running a generation", and a fallback would make those two identical on
  # the wire.
  defp version(%{request_path: "/api/version"} = conn, _opts) do
    stamp = OrcaHub.Cluster.CodeStamp.local()

    body =
      Jason.encode!(%{
        sha: OrcaHub.BuildInfo.sha(),
        built_at: OrcaHub.BuildInfo.built_at(),
        code_sha: stamp && Map.get(stamp, :base_sha),
        code: OrcaHub.Cluster.CodeStamp.to_json(stamp)
      })

    conn
    |> Plug.Conn.put_resp_content_type("application/json")
    |> Plug.Conn.send_resp(200, body)
    |> Plug.Conn.halt()
  end

  defp version(conn, _opts), do: conn

  # Restart readiness for THIS instance — "is anything in flight on this
  # node right now?". Unauthenticated for the same reason as `version/2`:
  # the deploy script polls it over plain localhost HTTP (directly for the
  # local instance, over ssh for mini/gb10) before restarting a systemd
  # agent, and has no bearer token to present.
  #
  # 200 when the question was answered, 503 when it could NOT be (hub
  # unreachable from an agent node, DB down, ...) — see
  # `OrcaHub.DrainStatus`. The status code and the `safe_to_restart`
  # boolean agree: an unanswerable check is a refusal, never a green light.
  #
  # `?ignore=<uuid>,<uuid>` drops those session ids from the counts — an
  # agent-driven deploy runs inside a session on the host it's restarting,
  # and would otherwise forever refuse to restart itself. Anything that
  # isn't a well-formed UUID is dropped here rather than handed to Ecto,
  # which would raise a cast error and turn a typo into a bogus "unknown".
  defp drain(%{request_path: "/api/drain"} = conn, _opts) do
    conn = Plug.Conn.fetch_query_params(conn)
    report = OrcaHub.DrainStatus.report(to_string(node()), ignore_ids(conn.query_params))
    status = if report.state == "ok", do: 200, else: 503

    conn
    |> Plug.Conn.put_resp_content_type("application/json")
    |> Plug.Conn.send_resp(status, Jason.encode!(report))
    |> Plug.Conn.halt()
  end

  defp drain(conn, _opts), do: conn

  @uuid_re ~r/\A[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\z/

  defp ignore_ids(%{"ignore" => ignore}) when is_binary(ignore) do
    ignore
    |> String.split(",", trim: true)
    |> Enum.map(&String.trim/1)
    |> Enum.filter(&Regex.match?(@uuid_re, &1))
  end

  defp ignore_ids(_params), do: []

  defp agent_mode_gate(conn, _opts) do
    if OrcaHub.Mode.agent?() and not agent_mode_allowed?(conn.path_info) do
      conn
      |> Plug.Conn.put_resp_content_type("text/plain")
      |> Plug.Conn.send_resp(404, "not found")
      |> Plug.Conn.halt()
    else
      conn
    end
  end

  # MCP Streamable HTTP endpoint (and any subpaths under it).
  defp agent_mode_allowed?(["mcp" | _]), do: true
  # k8s liveness/readiness probes.
  defp agent_mode_allowed?(["healthz"]), do: true
  # Deploy script polls this over plain HTTP; see `version/2` above.
  defp agent_mode_allowed?(["api", "version"]), do: true
  # Deploy script's pre-restart drain check; see `drain/2` above. Agent
  # nodes are exactly the instances this gates, so it MUST be allow-listed
  # here or it 404s on the three hosts that matter.
  defp agent_mode_allowed?(["api", "drain"]), do: true
  defp agent_mode_allowed?(_path_info), do: false
end
